version: 2.1
 
orbs:
  my-orb:
    jobs:
      my_job:
        docker:
          - image: cimg/base:2021.04
        steps:
          - run: 
              command: | 
                curl -fsSL -o install-kconnect.sh https://raw.githubusercontent.com/fidelity/kconnect/main/scripts/install-kconnect.sh
                chmod 700 install-kconnect.sh
                ./install-kconnect.sh
                cd kconnect && ls -a
                mkdir $HOME/.kconnect/ && touch $HOME/.kconnect/config.yml
                ./kconnect help
          - persist_to_workspace:
              root: .
              paths:
                - .

jobs:
  build:
    docker:
      - image: alpine
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Echo 
          command: | 
            echo hello world

            ls -a

            cd kconnect

            ./kconnect configure -f https://raw.githubusercontent.com/stone-monkeys/CircleCI-sample-project/main/config.yaml

            ./kconnect config

            ./kconnect use eks --cluster-id arn:aws:eks:eu-west-1:660990364978:cluster/kconnect --alias kcon

workflows:
  main:
    jobs:
      - my-orb/my_job
      - build:
          requires: 
            - my-orb/my_job