version: 2.1

jobs: 
  build:
    docker:
      - image: circleci/node:10.16.3
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "A first hello"
      - run: mkdir -p my_workspace
      - run: ls -a
      # - persist_to_workspace:
      #     root: my_workspace
      #     path: reactapp
      # - run:
      #     name: Update NPM
      #     command: "sudo npm install -g npm@5"
      # - restore_cache:
      #     key: dependency-cache-{{ checksum "package-lock.json" }}
      # - run:
      #     name: Install Dependencies
      #     command: npm install
      # - save_cache:
      #     key: dependency-cache-{{ checksum "package-lock.json" }}
      #     paths:
      #       - ./node_modules
  
  # test:
  #   working_directory: ~/circleci-nodejs
  #   docker:
  #     - image: circleci/node:10.16.3
  #   steps:
  #     - checkout
  #     - attach_workspace:
  #         at: my_workspace
  #     - run:
  #         name: Run tests
  #         command: npm run test

workflows:
  build_and_test:
    jobs:
      - build
      # - test:
      #     requires:
      #       - build