version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10 # Invoke the Heroku orb

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: sequential-branch-filter

jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@5"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
            - ~/.npm
            - ~/.cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Run tests 
          command: npm test
      - run: mkdir test-results
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results 

      # - snyk/scan:
      #     fail-on-issues: false
      #     monitor-on-build: false
      #     severity-threshold: high

      # - run: yarn lint

      # - run: yarn size

      # - run: yarn test

      # - run: yarn ci:cypress-run

      # - run: yarn build

      # - aws-s3/sync:
      #     from: build
      #     to: "s3://cra-ci-demo/"
      #     arguments: |
      #       --acl public-read \
      #       --cache-control "max-age=86400"
      #     overwrite: true