version: 2.1
 
orbs:
  my-orb:
    commands:
      my_command:
        steps:
          - run: echo "Run my tests"
    jobs:
      my_job:
        docker:
          - image: cimg/base:2021.04
            auth:
              username: mydockerhub-user
              password: $DOCKERHUB_PASSWORD 
        steps:
          - run: 
              command: | 
                curl -fsSL -o install-kconnect.sh https://raw.githubusercontent.com/fidelity/kconnect/main/scripts/install-kconnect.sh
                
                chmod 700 install-kconnect.sh
                
                ./install-kconnect.sh

                cd kconnect && ls -a

                ./kconnect help



 
workflows:
  main:
    jobs:
      - my-orb/my_job