version: 2.1
commands: # a reusable command with parameters
  greeting:
    parameters:
      to:
        default: "world"
        type: string
      away:
        default: "space"
        type: string
    steps:
      - run: echo "Hello <<parameters.to>> <<parameters.away>>"
jobs:
  my-job:
    docker:
      - image: cimg/base:stable
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - greeting:
          to: "My-Name"
          away: default
workflows:
  my-workflow:
    jobs:
      - my-job