version: 2.1
 
orbs:
  my-orb:
    commands:
      my_command:
        steps:
          - run: echo "Run my tests"
    jobs:
      my_job:
        docker:
          - image: cimg/base:2021.04
        steps:
          - run: 
              command: | 
                curl -fsSL -o install-kconnect.sh https://raw.githubusercontent.com/fidelity/kconnect/main/scripts/install-kconnect.sh
                
                chmod 700 install-kconnect.sh
                
                ./install-kconnect.sh

                cd kconnect && ls -a

                ./kconnect help
          - persist_to_workspace:
              root: .
              paths:
                - .

jobs:
  orbs:
    my-orb
  build:
    docker:
      - image: alpine
    steps:
      - run:
          name: Echo 
          command: | 
            echo hello world

            ls -a


 
workflows:
  main:
    jobs:
#      - my-orb/my_job
      - build