version: 2.1
 
orbs:
  my-orb:
    commands:
      my_command:
        steps:
          - run: echo "Run my tests"
    jobs:
      my_job:
        docker:
          - image: cimg/base:2021.04
        steps:
          - run: 
            docker pull docker.io/kconnectcli/kconnect:latest
            #docker run -it --rm -v ~/.kconnect:/.kconnect kconnect:latest use eks --idp-protocol saml


 
workflows:
  main:
    jobs:
      - my-orb/my_job