version: 2.1
 
orbs:
  param-test:
    commands:
      hello:
        parameters:
            image: 
              description: Description of the command
              type: string
        steps:
          - run:
              environment:
                PARAM_TO: <<parameters.image>>
              name: hello env
              command: sh test.sh

jobs:
  build:
    docker:
      - image: cimg/base:2021.04

    steps:
      - checkout
      - param-test/hello: 
            image: cimg/python:stable
          
workflows:
  main:
    jobs:
      - build
