version: 2.1
 
orbs:
  my-orb:
    jobs:
      my_job:
        docker:
          - image: cimg/base:2021.04
        steps:
          - run: 
              command: | 
                curl -fsSL -o install.sh https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
                chmod 700 install.sh
                ./install.sh
                
                brew help
          - persist_to_workspace:
              root: .
              paths:
                - .

jobs:
  build:
    docker:
      - image: alpine
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Echo 
          command: | 
            echo hello world

            ls -a

            cd kconnect

            ./kconnect help

workflows:
  main:
    jobs:
      - my-orb/my_job
      - build:
          requires: 
            - my-orb/my_job