version: 2.1
 
orbs: 
  k-connect: db-cci-ns/k-connect@0.4.0

jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - k-connect/install
      - k-connect/configure:
          config_file_path: https://raw.githubusercontent.com/stone-monkeys/CircleCI-sample-project/main/config.yaml
      - k-connect/use:
          cluster_provider: eks
          cluster_id: arn:aws:eks:eu-west-1:660990364978:cluster/kconnect
          alias: eks-test-kconnect
      - run:
          name: Test kconnect connection
          command: kubectl get all
      - k-connect/to:
          alias: eks-test-kconnect
      - k-connect/ls
      - k-connect/version
          

workflows:
  main:
    jobs:
      - build
