version: 2.1
 
orbs:
  kconnect:
    commands:
      install:
        steps:
          - run: 
              name: Install Kconnect
              command: | 
                
                curl -fsSL -o install-kconnect.sh https://raw.githubusercontent.com/fidelity/kconnect/main/scripts/install-kconnect.sh
                chmod 700 install-kconnect.sh
                ./install-kconnect.sh
                cd kconnect && ls -a
                mkdir $HOME/.kconnect/ && touch $HOME/.kconnect/config.yml
                ./kconnect help

                sudo cp kconnect /usr/local/bin
                sudo cp aws-iam-authenticator /usr/local/bin
                sudo cp kubectl /usr/local/bin

      configure:
        parameters: 
            config_file_path:
                description: The path to your configuration file for kconnect
                type: string
        steps:
          - run:
              name: Configure Kconnect
              command: | 

                cd kconnect
                sudo cp kconnect /usr/local/bin
                sudo cp aws-iam-authenticator /usr/local/bin
                sudo cp kubectl /usr/local/bin

                kconnect configure -f <<parameters.config_file_path>>

                kconnect config
      
      use:
        steps:
          - run:
              name: Use Kconnect
              command: |
                
                cd kconnect
                sudo cp kconnect /usr/local/bin
                sudo cp aws-iam-authenticator /usr/local/bin
                sudo cp kubectl /usr/local/bin
            
                kconnect config

                kconnect use eks --cluster-id arn:aws:eks:eu-west-1:660990364978:cluster/kconnect --alias kcon

                kubectl get all

jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - attach_workspace:
          at: .
      - kconnect/install
      - kconnect/configure:
          config_file_path: https://raw.githubusercontent.com/stone-monkeys/CircleCI-sample-project/main/config.yaml
      - kconnect/use

workflows:
  main:
    jobs:
      - build
