version: 2.1

jobs:
  build:
    working_directory: ~/circleci-nodejs
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: mkdir -p my_workspace
      - persist_to_workspace:
          root: my_workspace
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@5"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  
  test:
    working_directory: ~/circleci-nodejs
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - attach_workspace:
          at: my_workspace
      - run:
          name: Run tests
          command: npm run test

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build