version: 2.1
 
orbs:
  my-orb:
    commands:
      my_command:
        steps:
          - run: echo "Run my tests"
    jobs:
      my_job:
        docker:
          - image: cimg/base:2021.04
            auth:
              username: mydockerhub-user
              password: $DOCKERHUB_PASSWORD 
        steps:
          - run: docker pull docker.io/kconnectcli/kconnect:latest


 
workflows:
  main:
    jobs:
      - my-orb/my_job