version: 2.1

orbs: 
  aws-cli: circleci/aws-cli@2.0.6

jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: example
      - run: echo "Run your code here"
workflows:
  aws-cli:
    jobs:
      - aws-cli-example:
          context: aws

## Org settings go to context and create them