version: 2

workflows:
  version: 2
  build_and_test:
    jobs: 
      - build
      - test:
          requires:
            - build

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout # Checkout github repo and clone into virtual environment
      - run: echo "A first hello"
      - run: sleep 5
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A hello from test"
      - run: sleep 5
