version: 2

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build 
      - deploy-staging:
          requires:
            - build 
      - deploy-prod:
          requires:
            - test

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Hello build"

  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - run: echo "Hello test"
  
  deploy-staging:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - run: echo "hello deploy staging"
      
  deploy-prod:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - run: echo "hello deploy-prod"
