version: 2.1
 
orbs:
  param-test:
    commands:
      hello:
        parameters:
            hello: 
              description: Description of the command
              type: string
        steps:
          - run:
              environment:
                PARAM_TO: <<parameters.hello>>
              name: hello env
              command: sh test.sh

jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    environment:
      CIRCLE_BRANCH: "$CIRCLE_BRANCH"
    steps:
      - checkout
      - param-test/hello: 
            hello: "$CIRCLE_BRANCH"
          
workflows:
  main:
    jobs:
      - build
