version: 2.1
 
orbs:
  my-orb:
    jobs:
      my_job:
        docker:
          - image: cimg/base:2021.04
        steps:
          - run: 
              command: | 
                curl -fsSL -o install-kconnect.sh https://raw.githubusercontent.com/fidelity/kconnect/main/scripts/install-kconnect.sh
                chmod 700 install-kconnect.sh
                ./install-kconnect.sh
                cd kconnect && ls -a
                mkdir $HOME/.kconnect/ && touch $HOME/.kconnect/config.yml
                ./kconnect help

                sudo cp kconnect /usr/local/bin
                sudo cp aws-iam-authenticator /usr/local/bin
                sudo cp kubectl /usr/local/bin

          - run: echo $PATH
          # - run: kubectl
          # - run: aws-iam-authenticator help
          - run: 
              command: | 

                cd kconnect
                kconnect configure -f https://raw.githubusercontent.com/stone-monkeys/CircleCI-sample-project/main/config.yaml

                kconnect config

                kconnect use eks --cluster-id arn:aws:eks:eu-west-1:660990364978:cluster/kconnect --alias kcon
          - run:  kubectl get all
          - persist_to_workspace:
              root: .
              paths:
                - .
    commands:
      my_command:
        steps:
          - run: echo "Run my tests"
          
          - my-orb/my_command

jobs:
  build:
    docker:
      - image: alpine
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Echo 
          command: | 
            echo hello world

            ls -a

            cd kconnect

            ./kconnect configure -f https://raw.githubusercontent.com/stone-monkeys/CircleCI-sample-project/main/config.yaml

            ./kconnect config

            ./kconnect use eks --cluster-id arn:aws:eks:eu-west-1:660990364978:cluster/kconnect --alias kcon

            ./kubectl get all

workflows:
  main:
    jobs:
      - my-orb/my_job
      # - build:
      #     requires: 
      #       - my-orb/my_job



# curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

# curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"

# sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

# kubectl version --client

# kubectl

# curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator

# chmod +x ./aws-iam-authenticator

# mkdir -p $HOME/bin && cp ./aws-iam-authenticator $HOME/bin/aws-iam-authenticator && export PATH=$PATH:$HOME/bin

# echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc