version: 2.1
 
orbs:
  param-test:
    commands:
      get-image:
        parameters:
            image: 
              description: foo bar
              type: string
        steps:
          - run:
              environment:
                DOCKER_IMAGE: <<parameters.image>>
              name: image env
              command: sh test.sh

jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - param-test/get-image: 
            image: ${CIRCLE_BRANCH}
workflows:
  main:
    jobs:
      - build
