version: 2.1
 
orbs:
  my-orb:
    commands:
      my_command:
        steps:
          - run: echo "Run my tests"
    jobs:
      my_job:
        docker:
          - image: alpine
        steps:
          - run: 
              command: | 
                curl -fsSL -o install-kconnect.sh https://raw.githubusercontent.com/fidelity/kconnect/main/scripts/install-kconnect.sh
                
                chmod 700 install-kconnect.sh
                
                ./install-kconnect.sh

                cd kconnect && ls -a

                ./kconnect help



jobs:
  build:
    run: echo "hello world"

 
workflows:
  main:
    jobs:
      - build
      - my-orb/my_job