version: 2.1
 
orbs:
  my-orb:
    commands:
      my_command:
        steps:
          - run: echo "Run my tests"
    jobs:
      my_job:
        docker:
          - image: alpine
        steps:
          - run: echo "Run my tests"

 
workflows:
  main:
    jobs:
      - my-orb/my_job