version: 2

workflows:
  version: 2
  build_and_test:
    jobs:
      - sonar-analysis

jobs:
  sonar-analysis:
    docker:
      - image: docker/latest
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: /caches/coverage
      - run: 
          name: Sonar Analysis
          command: |
            mkdir -p artifacts
            cp -r /caches/coverage ./artifacts/coverage
            docker conatiner ps
