version: 2.1
 
orbs:
  kconnect:
    commands:
      install:
        steps:
          - run: 
              name: Install Kconnect
              command: | 
                
                curl -fsSL -o install-kconnect.sh https://raw.githubusercontent.com/fidelity/kconnect/main/scripts/install-kconnect.sh
                chmod 700 install-kconnect.sh
                ./install-kconnect.sh
                cd kconnect && ls -a
                mkdir $HOME/.kconnect/ && touch $HOME/.kconnect/config.yml
                ./kconnect help

                sudo cp kconnect /usr/local/bin
                sudo cp aws-iam-authenticator /usr/local/bin
                sudo cp kubectl /usr/local/bin

      configure:
        parameters: 
            config_file_path:
                description: File or remote location to use to set the default configuration
                type: string
        steps:
          - run:
              name: Configure Kconnect
              command: | 

                cd kconnect
                sudo cp kconnect /usr/local/bin
                sudo cp aws-iam-authenticator /usr/local/bin
                sudo cp kubectl /usr/local/bin

                kconnect configure -f <<parameters.config_file_path>>

                kconnect config
      
      use:
        parameters: 
            cluster_provider:
                description: The use command requires a target provider name
                type: string
            cluster_id:
                description: Id of the cluster to use
                type: string
            alias: 
                description: Friendly name to give to give the connection
                type: string
        steps:
          - run:
              name: Use Kconnect
              command: |
                
                cd kconnect
          
                kconnect use <<parameters.cluster_provider>> --cluster-id <<parameters.cluster_id>> --alias kcon

                kubectl get all

jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - attach_workspace:
          at: .
      - kconnect/install
      - kconnect/configure:
          config_file_path: https://raw.githubusercontent.com/stone-monkeys/CircleCI-sample-project/main/config.yaml
      - kconnect/use

workflows:
  main:
    jobs:
      - build
